# Generated by Django 6.0.1 on 2026-01-24 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RawJSONData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('display_name', models.CharField(blank=True, max_length=200, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('profile_image_url', models.URLField(blank=True, null=True)),
                ('profile_banner_url', models.URLField(blank=True, null=True)),
                ('followers', models.PositiveIntegerField(blank=True, null=True)),
                ('following', models.PositiveIntegerField(blank=True, null=True)),
                ('tweet_count', models.PositiveIntegerField(blank=True, null=True)),
                ('listed_count', models.PositiveIntegerField(blank=True, null=True)),
                ('like_count', models.PositiveIntegerField(blank=True, null=True)),
                ('media_count', models.PositiveIntegerField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('most_recent_tweet_id', models.CharField(blank=True, max_length=50, null=True)),
                ('pinned_tweet_id', models.CharField(blank=True, max_length=50, null=True)),
                ('protected', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='api.platform')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='api.target')),
            ],
            options={
                'ordering': ['-followers', '-tweet_count'],
                'unique_together': {('platform', 'username')},
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('text', models.TextField()),
                ('date', models.DateTimeField()),
                ('lang', models.CharField(blank=True, max_length=10, null=True)),
                ('reply_settings', models.CharField(blank=True, max_length=50, null=True)),
                ('possibly_sensitive', models.BooleanField(default=False)),
                ('edit_history_tweet_ids', models.JSONField(blank=True, null=True)),
                ('retweet_count', models.PositiveIntegerField(blank=True, null=True)),
                ('reply_count', models.PositiveIntegerField(blank=True, null=True)),
                ('like_count', models.PositiveIntegerField(blank=True, null=True)),
                ('quote_count', models.PositiveIntegerField(blank=True, null=True)),
                ('bookmark_count', models.PositiveIntegerField(blank=True, null=True)),
                ('impression_count', models.PositiveIntegerField(blank=True, null=True)),
                ('referenced_tweets', models.JSONField(blank=True, null=True)),
                ('context_annotations', models.JSONField(blank=True, null=True)),
                ('attachments', models.JSONField(blank=True, null=True)),
                ('entities', models.JSONField(blank=True, null=True)),
                ('is_video', models.BooleanField(default=False)),
                ('nlp_analysis', models.JSONField(blank=True, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='api.platform')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='api.profile')),
            ],
            options={
                'ordering': ['-date', '-like_count'],
            },
        ),
        migrations.CreateModel(
            name='CrossPlatformProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('display_name', models.CharField(blank=True, max_length=200, null=True)),
                ('url', models.URLField()),
                ('bio', models.TextField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.platform')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.target')),
            ],
        ),
    ]
