# Generated by Django 6.0.1 on 2026-02-03 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawjsondata',
            name='fetched_at',
        ),
        migrations.AlterField(
            model_name='rawjsondata',
            name='data',
            field=models.TextField(),
        ),
    ]
