# Generated by Django 6.0.1 on 2026-02-03 20:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_rawjsondata_fetched_at_alter_rawjsondata_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawjsondata',
            name='fetched_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
