# Generated by Django 6.0.1 on 2026-02-03 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rawjsondata_fetched_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='attachments',
        ),
        migrations.RemoveField(
            model_name='post',
            name='context_annotations',
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_video',
        ),
        migrations.RemoveField(
            model_name='post',
            name='nlp_analysis',
        ),
        migrations.RemoveField(
            model_name='post',
            name='platform',
        ),
    ]
