# Generated by Django 6.0.1 on 2026-02-03 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_post_attachments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='profile',
        ),
    ]
