# Generated by Django 6.0.1 on 2026-02-04 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_post_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text_analysis',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
