# Generated by Django 6.0.1 on 2026-03-18 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AlertCluster',
            new_name='Alert',
        ),
    ]
