from flask import Flask, send_from_directory, request, jsonify, send_file
from models import db, User, Note
from auth import auth_bp
from osint import basic_lookup
from graph import build_graph
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from io import BytesIO
import os
import jwt

app = Flask(__name__, static_folder="Frontend", static_url_path="")

# DATABASE
app.config["SQLALCHEMY_DATABASE_URI"] = os.environ.get("DATABASE_URL", "sqlite:///local.db")
app.config["SECRET_KEY"] = os.environ.get("SECRET_KEY", "dev")
db.init_app(app)

with app.app_context():
    db.create_all()

# AUTH ROUTES
app.register_blueprint(auth_bp)

# FRONTEND ROUTES
@app.route("/")
def serve_frontend():
    return send_from_directory("Frontend", "index.html")

@app.route("/<path:path>")
def serve_static(path):
    return send_from_directory("Frontend", path)

# OSINT API
@app.route("/api/check", methods=["POST"])
def check_user():
    data = request.json
    username = data.get("username")
    if not username:
        return jsonify({"error": "username missing"}), 400
    results = basic_lookup(username)
    return jsonify(results)

# GRAPH API
@app.route("/api/graph", methods=["POST"])
def graph_api():
    data = request.json
    username = data.get("username")
    if not username:
        return jsonify({"error": "username missing"}), 400
    graph = build_graph(username)
    return jsonify(graph)

# NOTES API
@app.route("/api/notes", methods=["POST"])
def add_note():
    data = request.json
    note = Note(
        username=data["username"],
        note=data["note"],
        tags=",".join(data.get("tags", []))
    )
    db.session.add(note)
    db.session.commit()
    return jsonify({"status": "ok"}), 201

@app.route("/api/notes/<username>", methods=["GET"])
def get_notes(username):
    notes = Note.query.filter_by(username=username).all()
    return jsonify([{
        "id": n.id,
        "note": n.note,
        "tags": n.tags.split(","),
        "created_at": str(n.created_at)
    } for n in notes])

# REPORT API
@app.route("/api/report/<username>", methods=["GET"])
def report(username):
    buffer = BytesIO()
    c = canvas.Canvas(buffer, pagesize=letter)

    c.drawString(100, 750, f"OSINT Report - {username}")
    c.drawString(100, 720, "Generated by OSINT MVP")

    c.showPage()
    c.save()

    buffer.seek(0)
    return send_file(buffer, mimetype="application/pdf",
                     download_name=f"{username}_report.pdf",
                     as_attachment=True)

if __name__ == "__main__":
    port = int(os.environ.get("PORT", 5000))
    app.run(host="0.0.0.0", port=port)
